// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbx0ptdf7WpqllaXHFKlwqvpmx0I-16Ro',
    appId: '1:365879353302:web:e79b03d1423d0100808e77',
    messagingSenderId: '365879353302',
    projectId: 'message-board-app-66f05',
    authDomain: 'message-board-app-66f05.firebaseapp.com',
    storageBucket: 'message-board-app-66f05.firebasestorage.app',
    measurementId: 'G-9VGD12S77V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCydRKOabErVoeqqz8N2nQ9i_-FsLzPAqY',
    appId: '1:365879353302:android:54a8ffe4354d28a9808e77',
    messagingSenderId: '365879353302',
    projectId: 'message-board-app-66f05',
    storageBucket: 'message-board-app-66f05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3maSiL9r2ZnVFkxD2UO9hienx_1Qo7vs',
    appId: '1:365879353302:ios:4429a879427bd9b3808e77',
    messagingSenderId: '365879353302',
    projectId: 'message-board-app-66f05',
    storageBucket: 'message-board-app-66f05.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3maSiL9r2ZnVFkxD2UO9hienx_1Qo7vs',
    appId: '1:365879353302:ios:4429a879427bd9b3808e77',
    messagingSenderId: '365879353302',
    projectId: 'message-board-app-66f05',
    storageBucket: 'message-board-app-66f05.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbx0ptdf7WpqllaXHFKlwqvpmx0I-16Ro',
    appId: '1:365879353302:web:49f8964c9c5fd35a808e77',
    messagingSenderId: '365879353302',
    projectId: 'message-board-app-66f05',
    authDomain: 'message-board-app-66f05.firebaseapp.com',
    storageBucket: 'message-board-app-66f05.firebasestorage.app',
    measurementId: 'G-R83M2LRLRW',
  );
}
